[main]
h = move -5 0
j = move 0 5
k = move 0 -5
l = move 5 0
H = move -50 0
J = move 0 50
K = move 0 -50
L = move 50 0
left = move -5 0
down = move 0 5
up = move 0 -5
right = move 5 0
g = grid
f = hint
Mouse1 = click 1
Mouse2 = click 3
Mouse3 = click 2
shift+Mouse1 = click 3
ScrollUp = scroll -20
ScrollDown = scroll 20
Tab = history
Escape = exit
Return = exit
q = exit
